diff --git a/ant-cnn/ant-cnn.ipynb b/ant-cnn/ant-cnn.ipynb
index 27b1e94..e8c9aed 100644
--- a/ant-cnn/ant-cnn.ipynb
+++ b/ant-cnn/ant-cnn.ipynb
@@ -2,581 +2,9 @@
  "cells": [
   {
    "cell_type": "code",
-   "execution_count": 3,
+   "execution_count": 81,
    "metadata": {},
-   "outputs": [
-    {
-     "name": "stderr",
-     "output_type": "stream",
-     "text": [
-      "Using TensorFlow backend.\n",
-      "C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py:3201: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
-      "  if training is 1 or training is True:\n",
-      "C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py:3207: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
-      "  elif training is 0 or training is False:\n",
-      "ERROR:root:Internal Python error in the inspect module.\n",
-      "Below is the traceback from this internal error.\n",
-      "\n",
-      "ERROR:root:Internal Python error in the inspect module.\n",
-      "Below is the traceback from this internal error.\n",
-      "\n"
-     ]
-    },
-    {
-     "name": "stdout",
-     "output_type": "stream",
-     "text": [
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3331, in run_code\n",
-      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
-      "  File \"<ipython-input-3-301b462f29c8>\", line 1, in <module>\n",
-      "    from preprocess import *\n",
-      "  File \"C:\\Users\\heyjo\\Documents\\School\\Capstone\\intellichirp-snaw-NN\\NN\\ant-cnn\\preprocess.py\", line 4, in <module>\n",
-      "    from keras.utils import to_categorical\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
-      "    from . import utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
-      "    from . import conv_utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
-      "    from .. import backend as K\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
-      "    from .load_backend import epsilon\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
-      "    from .tensorflow_backend import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
-      "    import tensorflow as tf\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
-      "    from tensorflow_core import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
-      "    from tensorflow.python.tools import module_util as _module_util\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
-      "    raise ImportError(msg)\n",
-      "ImportError: Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "\n",
-      "Failed to load the native TensorFlow runtime.\n",
-      "\n",
-      "See https://www.tensorflow.org/install/errors\n",
-      "\n",
-      "for some common reasons and solutions.  Include the entire stack trace\n",
-      "above this error message when asking for help.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
-      "    stb = value._render_traceback_()\n",
-      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1148, in get_records\n",
-      "    # Try the default getinnerframes and Alex's: Alex's fixes some\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
-      "    inspect.findsource = findsource\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
-      "    def _fixed_getinnerframes(etb, context=1, tb_offset=0):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 1503, in getinnerframes\n",
-      "    def trace(context=1):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 1461, in getframeinfo\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 708, in getsourcefile\n",
-      "    _filename = getsourcefile(object) or getfile(object)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 745, in getmodule\n",
-      "    # Check the main module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
-      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
-      "  File \"<frozen importlib._bootstrap>\", line 961, in _find_and_load_unlocked\n",
-      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
-      "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
-      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
-      "  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
-      "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
-      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
-      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 42, in <module>\n",
-      "    from . _api.v2 import audio\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\_api\\v2\\audio\\__init__.py\", line 10, in <module>\n",
-      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\ops\\gen_audio_ops.py\", line 8, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
-      "    raise ImportError(msg)\n",
-      "ImportError: Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3331, in run_code\n",
-      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
-      "  File \"<ipython-input-3-301b462f29c8>\", line 1, in <module>\n",
-      "    from preprocess import *\n",
-      "  File \"C:\\Users\\heyjo\\Documents\\School\\Capstone\\intellichirp-snaw-NN\\NN\\ant-cnn\\preprocess.py\", line 4, in <module>\n",
-      "    from keras.utils import to_categorical\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
-      "    from . import utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
-      "    from . import conv_utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
-      "    from .. import backend as K\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
-      "    from .load_backend import epsilon\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
-      "    from .tensorflow_backend import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
-      "    import tensorflow as tf\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
-      "    from tensorflow_core import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
-      "    from tensorflow.python.tools import module_util as _module_util\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
-      "    raise ImportError(msg)\n",
-      "ImportError: Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "\n",
-      "Failed to load the native TensorFlow runtime.\n",
-      "\n",
-      "See https://www.tensorflow.org/install/errors\n",
-      "\n",
-      "for some common reasons and solutions.  Include the entire stack trace\n",
-      "above this error message when asking for help.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
-      "    stb = value._render_traceback_()\n",
-      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "\n",
-      "Failed to load the native TensorFlow runtime.\n",
-      "\n",
-      "See https://www.tensorflow.org/install/errors\n",
-      "\n",
-      "for some common reasons and solutions.  Include the entire stack trace\n",
-      "above this error message when asking for help.\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3331, in run_code\n",
-      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
-      "  File \"<ipython-input-3-301b462f29c8>\", line 1, in <module>\n",
-      "    from preprocess import *\n",
-      "  File \"C:\\Users\\heyjo\\Documents\\School\\Capstone\\intellichirp-snaw-NN\\NN\\ant-cnn\\preprocess.py\", line 4, in <module>\n",
-      "    from keras.utils import to_categorical\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
-      "    from . import utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
-      "    from . import conv_utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
-      "    from .. import backend as K\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
-      "    from .load_backend import epsilon\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
-      "    from .tensorflow_backend import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
-      "    import tensorflow as tf\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
-      "    from tensorflow_core import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
-      "    from tensorflow.python.tools import module_util as _module_util\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
-      "    raise ImportError(msg)\n",
-      "ImportError: Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "\n",
-      "Failed to load the native TensorFlow runtime.\n",
-      "\n",
-      "See https://www.tensorflow.org/install/errors\n",
-      "\n",
-      "for some common reasons and solutions.  Include the entire stack trace\n",
-      "above this error message when asking for help.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
-      "    stb = value._render_traceback_()\n",
-      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3254, in run_ast_nodes\n",
-      "    if (await self.run_code(code, result,  async_=asy)):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3348, in run_code\n",
-      "    self.showtraceback(running_compiled_code=True)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
-      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1414, in structured_traceback\n",
-      "    self.tb = tb[0]\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1314, in structured_traceback\n",
-      "    mode = self.mode\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1183, in structured_traceback\n",
-      "    formatted_exceptions = formatted_exception\n",
-      "TypeError: can only concatenate str (not \"list\") to str\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
-      "    stb = value._render_traceback_()\n",
-      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n"
-     ]
-    },
-    {
-     "name": "stdout",
-     "output_type": "stream",
-     "text": [
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1148, in get_records\n",
-      "    # Try the default getinnerframes and Alex's: Alex's fixes some\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
-      "    inspect.findsource = findsource\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
-      "    def _fixed_getinnerframes(etb, context=1, tb_offset=0):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 1503, in getinnerframes\n",
-      "    def trace(context=1):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 1461, in getframeinfo\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 708, in getsourcefile\n",
-      "    _filename = getsourcefile(object) or getfile(object)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\inspect.py\", line 745, in getmodule\n",
-      "    # Check the main module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
-      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
-      "  File \"<frozen importlib._bootstrap>\", line 961, in _find_and_load_unlocked\n",
-      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
-      "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
-      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
-      "  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
-      "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
-      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
-      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 42, in <module>\n",
-      "    from . _api.v2 import audio\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\_api\\v2\\audio\\__init__.py\", line 10, in <module>\n",
-      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\ops\\gen_audio_ops.py\", line 8, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
-      "    raise ImportError(msg)\n",
-      "ImportError: Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3331, in run_code\n",
-      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
-      "  File \"<ipython-input-3-301b462f29c8>\", line 1, in <module>\n",
-      "    from preprocess import *\n",
-      "  File \"C:\\Users\\heyjo\\Documents\\School\\Capstone\\intellichirp-snaw-NN\\NN\\ant-cnn\\preprocess.py\", line 4, in <module>\n",
-      "    from keras.utils import to_categorical\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
-      "    from . import utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
-      "    from . import conv_utils\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
-      "    from .. import backend as K\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
-      "    from .load_backend import epsilon\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
-      "    from .tensorflow_backend import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
-      "    import tensorflow as tf\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
-      "    from tensorflow_core import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
-      "    from tensorflow.python.tools import module_util as _module_util\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
-      "    module = self._load()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
-      "    module = _importlib.import_module(self.__name__)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
-      "    from tensorflow.python import pywrap_tensorflow\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
-      "    raise ImportError(msg)\n",
-      "ImportError: Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "\n",
-      "Failed to load the native TensorFlow runtime.\n",
-      "\n",
-      "See https://www.tensorflow.org/install/errors\n",
-      "\n",
-      "for some common reasons and solutions.  Include the entire stack trace\n",
-      "above this error message when asking for help.\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
-      "    stb = value._render_traceback_()\n",
-      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3254, in run_ast_nodes\n",
-      "    if (await self.run_code(code, result,  async_=asy)):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3348, in run_code\n",
-      "    self.showtraceback(running_compiled_code=True)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2046, in showtraceback\n",
-      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1414, in structured_traceback\n",
-      "    self.tb = tb[0]\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1314, in structured_traceback\n",
-      "    mode = self.mode\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1183, in structured_traceback\n",
-      "    formatted_exceptions = formatted_exception\n",
-      "TypeError: can only concatenate str (not \"list\") to str\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
-      "    stb = value._render_traceback_()\n",
-      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
-      "\n",
-      "During handling of the above exception, another exception occurred:\n",
-      "\n",
-      "Traceback (most recent call last):\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
-      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
-      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
-      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 242, in load_module\n",
-      "    else:\n",
-      "  File \"C:\\Users\\heyjo\\.conda\\envs\\capstone\\lib\\imp.py\", line 342, in load_dynamic\n",
-      "    name=name, loader=loader, origin=path)\n",
-      "ImportError: Module use of python36.dll conflicts with this version of Python.\n",
-      "\n",
-      "\n",
-      "Failed to load the native TensorFlow runtime.\n",
-      "\n",
-      "See https://www.tensorflow.org/install/errors\n",
-      "\n",
-      "for some common reasons and solutions.  Include the entire stack trace\n",
-      "above this error message when asking for help.\n"
-     ]
-    },
-    {
-     "ename": "TypeError",
-     "evalue": "can only concatenate str (not \"list\") to str",
-     "output_type": "error",
-     "traceback": [
-      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
-      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     57\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 58\u001b[1;33m   \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[1;33m*\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     59\u001b[0m   \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0m__version__\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     27\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0m_mod\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 28\u001b[1;33m     \u001b[0m_pywrap_tensorflow_internal\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     29\u001b[0m     \u001b[1;32mdel\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36mswig_import_helper\u001b[1;34m()\u001b[0m\n\u001b[0;32m     23\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 24\u001b[1;33m                 \u001b[0m_mod\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mimp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mload_module\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'_pywrap_tensorflow_internal'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfp\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpathname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     25\u001b[0m             \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\imp.py\u001b[0m in \u001b[0;36mload_module\u001b[1;34m(name, file, filename, details)\u001b[0m\n\u001b[0;32m    241\u001b[0m                 \u001b[1;32mreturn\u001b[0m \u001b[0mload_dynamic\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilename\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mopened_file\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 242\u001b[1;33m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    243\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mload_dynamic\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilename\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfile\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\imp.py\u001b[0m in \u001b[0;36mload_dynamic\u001b[1;34m(name, path, file)\u001b[0m\n\u001b[0;32m    341\u001b[0m         spec = importlib.machinery.ModuleSpec(\n\u001b[1;32m--> 342\u001b[1;33m             name=name, loader=loader, origin=path)\n\u001b[0m\u001b[0;32m    343\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0m_load\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mspec\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;31mImportError\u001b[0m: Module use of python36.dll conflicts with this version of Python.",
-      "\nDuring handling of the above exception, another exception occurred:\n",
-      "\nDuring handling of the above exception, another exception occurred:\n",
-      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2043\u001b[0m                         \u001b[1;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2044\u001b[1;33m                         \u001b[0mstb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2045\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;31mAttributeError\u001b[0m: 'ImportError' object has no attribute '_render_traceback_'",
-      "\nDuring handling of the above exception, another exception occurred:\n",
-      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mrun_code\u001b[1;34m(self, code_obj, result, async_)\u001b[0m\n\u001b[0;32m   3346\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mresult\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3347\u001b[0m                 \u001b[0mresult\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror_in_exec\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msys\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 3348\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshowtraceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrunning_compiled_code\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3349\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3350\u001b[0m             \u001b[0moutflag\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2044\u001b[0m                         \u001b[0mstb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2045\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2046\u001b[1;33m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[0m\u001b[0;32m   2047\u001b[0m                                             value, tb, tb_offset=tb_offset)\n\u001b[0;32m   2048\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1412\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtuple\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1413\u001b[0m             \u001b[1;31m# tb is a tuple if this is a chained exception.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1414\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1415\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1416\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1312\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mstructured_traceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m5\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1313\u001b[0m         \u001b[0mtb_offset\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtb_offset\u001b[0m \u001b[1;32mif\u001b[0m \u001b[0mtb_offset\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mNone\u001b[0m \u001b[1;32melse\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1314\u001b[1;33m         \u001b[0mmode\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmode\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1315\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mmode\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mverbose_modes\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1316\u001b[0m             \u001b[1;31m# Verbose modes need a full traceback\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;32m~\\.conda\\envs\\capstone\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1181\u001b[0m         \u001b[0mchained_exceptions_tb_offset\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1182\u001b[0m         \u001b[0mlines_of_context\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m3\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1183\u001b[1;33m         \u001b[0mformatted_exceptions\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mformatted_exception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1184\u001b[0m         \u001b[0mexception\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_parts_of_chained_exception\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1185\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mexception\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
-      "\u001b[1;31mTypeError\u001b[0m: can only concatenate str (not \"list\") to str"
-     ]
-    }
-   ],
+   "outputs": [],
    "source": [
     "from preprocess import *\n",
     "import keras\n",
@@ -590,7 +18,7 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 3,
+   "execution_count": 82,
    "metadata": {},
    "outputs": [
     {
@@ -598,8 +26,8 @@
       "text/html": [
        "\n",
        "                Logging results to <a href=\"https://wandb.com\" target=\"_blank\">Weights & Biases</a> <a href=\"https://docs.wandb.com/integrations/jupyter.html\" target=\"_blank\">(Documentation)</a>.<br/>\n",
-       "                Project page: <a href=\"https://app.wandb.ai/stevenenriquez/uncategorized\" target=\"_blank\">https://app.wandb.ai/stevenenriquez/uncategorized</a><br/>\n",
-       "                Run page: <a href=\"https://app.wandb.ai/stevenenriquez/uncategorized/runs/iqcktkix\" target=\"_blank\">https://app.wandb.ai/stevenenriquez/uncategorized/runs/iqcktkix</a><br/>\n",
+       "                Project page: <a href=\"https://app.wandb.ai/joshekruse/intellichirp-snaw-NN\" target=\"_blank\">https://app.wandb.ai/joshekruse/intellichirp-snaw-NN</a><br/>\n",
+       "                Run page: <a href=\"https://app.wandb.ai/joshekruse/intellichirp-snaw-NN/runs/bbga5a62\" target=\"_blank\">https://app.wandb.ai/joshekruse/intellichirp-snaw-NN/runs/bbga5a62</a><br/>\n",
        "            "
       ],
       "text/plain": [
@@ -613,17 +41,18 @@
      "name": "stderr",
      "output_type": "stream",
      "text": [
-      "Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable\n",
-      "Saving vectors of label - 'bus': 100%|███████████████████████████████████████████████| 109/109 [00:04<00:00, 22.23it/s]\n",
-      "Saving vectors of label - 'car_horn': 100%|████████████████████████████████████████████| 40/40 [00:00<00:00, 68.21it/s]\n",
-      "Saving vectors of label - 'chainsaw': 100%|████████████████████████████████████████████| 40/40 [00:00<00:00, 43.29it/s]\n",
-      "Saving vectors of label - 'cow': 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 54.85it/s]\n",
-      "Saving vectors of label - 'engine': 100%|██████████████████████████████████████████████| 40/40 [00:00<00:00, 54.93it/s]\n",
-      "Saving vectors of label - 'footsteps': 100%|███████████████████████████████████████████| 40/40 [00:00<00:00, 65.51it/s]\n",
-      "Saving vectors of label - 'hand_saw': 100%|████████████████████████████████████████████| 40/40 [00:00<00:00, 53.98it/s]\n",
-      "Saving vectors of label - 'hen': 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 65.41it/s]\n",
-      "Saving vectors of label - 'rooster': 100%|█████████████████████████████████████████████| 40/40 [00:00<00:00, 68.64it/s]\n",
-      "Saving vectors of label - 'siren': 100%|███████████████████████████████████████████████| 40/40 [00:00<00:00, 55.64it/s]\n"
+      "Saving vectors of label - 'bus': 100%|███████████████████████████████████████████████| 109/109 [00:04<00:00, 22.81it/s]\n",
+      "Saving vectors of label - 'car_horn': 100%|████████████████████████████████████████████| 40/40 [00:00<00:00, 49.03it/s]\n",
+      "Saving vectors of label - 'chainsaw': 100%|████████████████████████████████████████████| 40/40 [00:00<00:00, 50.39it/s]\n",
+      "Saving vectors of label - 'cow': 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 52.63it/s]\n",
+      "Saving vectors of label - 'engine': 100%|██████████████████████████████████████████████| 40/40 [00:00<00:00, 63.46it/s]\n",
+      "Saving vectors of label - 'footsteps': 100%|███████████████████████████████████████████| 40/40 [00:00<00:00, 47.57it/s]\n",
+      "Saving vectors of label - 'hand_saw': 100%|████████████████████████████████████████████| 40/40 [00:00<00:00, 55.32it/s]\n",
+      "Saving vectors of label - 'hen': 100%|█████████████████████████████████████████████████| 40/40 [00:00<00:00, 79.26it/s]\n",
+      "Saving vectors of label - 'NO': 100%|████████████████████████████████████████████████| 802/802 [00:14<00:00, 54.85it/s]\n",
+      "Saving vectors of label - 'rooster': 100%|█████████████████████████████████████████████| 40/40 [00:00<00:00, 55.32it/s]\n",
+      "Saving vectors of label - 'siren': 100%|███████████████████████████████████████████████| 40/40 [00:00<00:00, 67.52it/s]\n",
+      "Saving vectors of label - 'train': 100%|███████████████████████████████████████████████| 40/40 [00:00<00:00, 55.86it/s]\n"
      ]
     }
    ],
@@ -637,12 +66,13 @@
     "# Save data to array file first\n",
     "save_data_to_array(max_len=config.max_len, n_mfcc=config.buckets)\n",
     "\n",
-    "labels=[\"bus\", \"car_horn\", \"chainsaw\", \"cow\", \"engine\", \"footsteps\", \"hand_saw\", \"hen\", \"rooster\", \"siren\"]"
+    "labels=np.array([\"bus\", \"car_horn\", \"chainsaw\", \"cow\", \"engine\", \"footsteps\", \n",
+    "                 \"hand_saw\", \"hen\", \"NO\", \"rooster\", \"siren\", \"train\"])"
    ]
   },
   {
    "cell_type": "code",
-   "execution_count": 4,
+   "execution_count": 83,
    "metadata": {},
    "outputs": [],
    "source": [
@@ -652,17 +82,9 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 5,
+   "execution_count": null,
    "metadata": {},
-   "outputs": [
-    {
-     "name": "stderr",
-     "output_type": "stream",
-     "text": [
-      "Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable\n"
-     ]
-    }
-   ],
+   "outputs": [],
    "source": [
     "# Setting channels to 1 to generalize stereo sound to 1 channel\n",
     "channels = 1\n",
@@ -670,7 +92,7 @@
     "config.batch_size = 100\n",
     "\n",
     "# Number of classes\n",
-    "num_classes = 10\n",
+    "num_classes = 12\n",
     "\n",
     "# Reshape X_train and X_test to include a 4th dimension (channels)\n",
     "X_train = X_train.reshape(X_train.shape[0], config.buckets, config.max_len, channels)\n",
@@ -679,29 +101,9 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 6,
+   "execution_count": null,
    "metadata": {},
-   "outputs": [
-    {
-     "name": "stdout",
-     "output_type": "stream",
-     "text": [
-      "3.0\n"
-     ]
-    },
-    {
-     "data": {
-      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAKQAAAD4CAYAAABi+U3NAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAQBElEQVR4nO3dfYxc1X3G8e8zu+tXTGzi2LGxS2jrohpa3MoyjVBVKA2xEYrTKm1tVa3bUjmNitRIjVTaqqFK+wdVlUZqQCFusCBtAvQlTizFAixaiSDlhYWagAsE1yJlY2Qn2LGhBtu78+sfe40m45mdc+fOsGdnno9kzdx7z9x7ZvfZOy/H53cVEZjlojbbHTBr5EBaVhxIy4oDaVlxIC0ro7PdgVbmaX4sYHFSW9XS/6ZiwbzktlMLR5Lb1seSm1JP/YnXMvj2QyXaJvZ38vs/ZOq1/2u75ywDuYDFXKMbktrWFi5K3m/89OXJbU+svzi57etr0n9zZ5bXk9pNLUprB5QLThmj6X2ozZ9KanfkL++aeT/JRzR7G1QKpKTNkl6QdEjSbS22z5f0YLH9m5LeU+V4Nvi6DqSkEeAuYAuwHtguaX1Ts1uAExHxk8CngL/t9ng2HKqcITcBhyLicEScBR4Atja12QrcV9z/N+AGSf16x2MDoEogLwVeblieKNa1bBMRk8BJ4J2tdiZpp6RxSePnOFOhWzaXVQlkqzNd82f/lDbTKyN2RcTGiNg4xvwK3bK5rEogJ4C1DctrgCPt2kgaBd4BHK9wTBtwVQL5BLBO0uWS5gHbgL1NbfYCO4r7HwL+I/z/3WwGXX8xHhGTkm4FHgZGgN0RcVDSJ4DxiNgL3AP8k6RDTJ8Zt/Wi0za4lOMJ68d/ZnH8zZeuTGq7dOR08n6vmvdqctt3jaS/j52v9LHDc5E2otEvddJHX/rR11/acpT/evps229aPFJjWXEgLSsOpGXFgbSsOJCWFQfSsuJAWlYcSMuKA2lZcSAtK1lO8np9agGPn/qpnu/3n88tTG57/Ez65LGTZxYktz03lTabcaqe/v+Y6/X088pkibY1pQ8rj9TShiS/c/qemY+ZfESzt4EDaVlxIC0rDqRlxYG0rDiQlhUH0rJSpXLFWkn/Kek5SQcl/XGLNtdJOinpQPHv49W6a4Ouyhfjk8CfRMRTkpYAT0raHxH/3dTuaxFxc4Xj2BDp+gwZEa9ExFPF/deA57iwcoVZKT0ZOiyqmv0c8M0Wm98r6Wmmiwh8LCIOttnHTmAnwJJVi1g4cjbp2G9MpRchnYz0v7+LxtLLuVwyP33m41gtbSbfqErUZizRdn5tclbbHp335ozbK3+okXQR8O/ARyPiVNPmp4DLIuJq4NPAl9vtp7GUyqKlLqUyrKrWhxxjOoxfiIgvNW+PiFMR8Xpxfx8wJml5lWPaYKvyKVtMV6Z4LiL+vk2bd58vvydpU3G89Nn6NnSqvIe8Fvht4BlJB4p1fw78GEBE3M10PZ+PSJoE3gC2ubaPzaRKbZ/H6VBuPSLuBO7s9hg2fDxSY1lxIC0rDqRlxYG0rDiQlpUsZx2OqM6y0fThuHRp108EeHMqvQhpmbb1SJtNWGbG36jSC4uW2m/iTEKAWutrGVzgTIeLPfoMaVlxIC0rDqRlxYG0rDiQlhUH0rLiQFpWHEjLigNpWclypCaAc5FWRzF15APgknnpoz9l2vZD6shHWaOJk8wAxkqMAKX+vjrt02dIy4oDaVnpxTTYlyQ9U5RKGW+xXZL+QdIhSd+W9PNVj2mDq1fvIa+PiB+02bYFWFf8uwb4THFrdoG34yV7K/D5mPYNYKmkVW/DcW0O6kUgA3hE0pNFOZRmlwIvNyxP0KIGkKSdksYljZ8+kVZGxQZPL16yr42II5JWAPslPR8RjzVsb/W9zAXfaUTELmAXwOorl3ru9pCqfIaMiCPF7TFgD7CpqckEsLZheQ3ThafMLlC1ts/iojYkkhYDNwLPNjXbC/xO8Wn7F4CTEfFKlePa4Kr6kr0S2FOU7xkFvhgRD0n6Q3irnMo+4CbgEHAa+L2Kx7QBVimQEXEYuLrF+rsb7gfwR1WOM5OFI+eS2148OnNtwkan6+l1JztNXOrGCGXqQ6a/5S4zHFhqv5G230779EiNZcWBtKw4kJYVB9Ky4kBaVhxIy4oDaVlxIC0rDqRlxYG0rGQ567BGsKCWNiS4ROnDgWUsGUnfb+qMu36ZKnHJvDLGSlxaLtVIh8vg+QxpWXEgLSsOpGXFgbSsOJCWFQfSsuJAWlaqXC/7iqJ8yvl/pyR9tKnNdZJONrT5ePUu2yCrcnniF4ANAJJGgO8xPQ222dci4uZuj2PDpVcv2TcA/xMR3+3R/mxI9WrocBtwf5tt75X0NNPFAT4WEQdbNSrKsOwEWLpqQY+69aPerKdfAq5fsw77MUOxzOzAfs1mTB0+PVefuV0vyvHNAz4A/GuLzU8Bl0XE1cCngS+3209E7IqIjRGxcfGy9DDYYOnFS/YW4KmIONq8ISJORcTrxf19wJik5T04pg2oXgRyO21eriW9W0VZC0mbiuO92oNj2oCq9IZG0iLgfcCHG9Y1llH5EPARSZPAG8C2opKFWUtVS6mcBt7ZtK6xjMqdwJ1VjmHDxSM1lhUH0rLiQFpWHEjLigNpWcly1mEdpQ/zlfiTOhPpT7fMTMIyQ2xlCqym6tdwYBm1xG/z1OHSlD5DWlYcSMuKA2lZcSAtKw6kZcWBtKw4kJYVB9Ky4kBaVhxIy0qWQ4dllCnWeVGJIqSLaukXkS/Th3rLy4e/Pfssu98yUgvM1joMc/oMaVlJCqSk3ZKOSXq2Yd0lkvZLerG4XdbmsTuKNi9K2tGrjttgSj1D3gtsblp3G/BoRKwDHi2Wf4SkS4DbgWuATcDt7YJrBomBjIjHgONNq7cC9xX37wM+2OKh7wf2R8TxiDgB7OfCYJu9pcp7yJUR8QpAcbuiRZtLgZcblieKdWYt9ftDTauPfy3/J6eknZLGJY2fPpH+CdcGS5VAHpW0CqC4PdaizQSwtmF5DdNFpy7QWNtnkWv7DK0qgdwLnP/UvAP4Sos2DwM3SlpWfJi5sVhn1lLq1z73A18HrpA0IekW4A7gfZJeZLqcyh1F242SPgcQEceBvwaeKP59olhn1lLSSE1EbG+z6YYWbceBP2hY3g3s7qp3NnSyHDoUna+J142R1p+nWhpLHAqDcjMU64lDd2OaSt5nmeHAc/TnuoypP4PoMMzpoUPLigNpWXEgLSsOpGXFgbSsOJCWFQfSsuJAWlYcSMuKA2lZyXLosIwyM+7KXOuwTHHTfqiVGOYsI3V2IJQbvkwdOuxUXNVnSMuKA2lZcSAtKw6kZcWBtKw4kJYVB9Ky0jGQber6/J2k5yV9W9IeSUvbPPYlSc9IOiBpvJcdt8GUcoa8lwvLn+wHroqInwW+A/zZDI+/PiI2RMTG7rpow6RjIFvV9YmIRyJislj8BtMFAMwq68X42O8DD7bZFsAjkgL4bETsarcTSTuBnQAXr1qYPBR1rp4+i67M7MAz9fQfTepMwn6plZihWeZah2WGDuuRNoTb6XdQKZCS/gKYBL7Qpsm1EXFE0gpgv6TnizPuBYqw7gJYfeXS/gzkWva6/tMuio/eDPxWROtLgUbEkeL2GLCH6RqRZm11FUhJm4E/BT4QEafbtFksacn5+0zX9Xm2VVuz81K+9mlV1+dOYAnTL8MHJN1dtF0taV/x0JXA45KeBr4FfDUiHurLs7CB0fE9ZJu6Pve0aXsEuKm4fxi4ulLvbOh4pMay4kBaVhxIy4oDaVlxIC0rWc46rFNLniE4WU//myozbHbRyJnktmWkDklOlThXpA7bldWv/c7EZ0jLigNpWXEgLSsOpGXFgbSsOJCWFQfSsuJAWlYcSMtKliM1ZYzW0ic4lZm01K+2K+adSmpX5jJ4/VJmUtxUYp3OsdrMPyufIS0rDqRlpdtSKn8l6XvFfJoDkm5q89jNkl6QdEjSbb3suA2mbkupAHyqKJGyISL2NW+UNALcBWwB1gPbJa2v0lkbfF2VUkm0CTgUEYcj4izwALC1i/3YEKnyHvLWovrZbknLWmy/FHi5YXmiWNeSpJ2SxiWNnz7Rn/+LaPnrNpCfAX4C2AC8AnyyRZtW3wO0/S4jInZFxMaI2Lho2fwuu2VzXVeBjIijETEVEXXgH2ldImUCWNuwvAY40s3xbHh0W0plVcPir9K6RMoTwDpJl0uaB2wD9nZzPBseHUdqilIq1wHLJU0AtwPXSdrA9EvwS8CHi7argc9FxE0RMSnpVuBhYATYHREH+/IsbGD0rZRKsbwPuOAroU5q1EtdAi1VmVqSr04uTm5bppbkSOJEs9ESw5FlJq91urRbt1L7MNnhd+CRGsuKA2lZcSAtKw6kZcWBtKw4kJYVB9Ky4kBaVhxIy4oDaVnJctahSJ/JN1Xism6dZrw1ulhvJrctU0exH/Uhy+hX3cl6Yp3OeofZiT5DWlYcSMuKA2lZcSAtKw6kZcWBtKw4kJaVlDk1u5m+UPuxiLiqWPcgcEXRZCnww4jY0OKxLwGvAVPAZERs7FG/bUClfEt7L9PXx/78+RUR8Zvn70v6JHByhsdfHxE/6LaDNlxSJnk9Juk9rbZJEvAbwC/3tls2rKoOHf4icDQiXmyzPYBHJAXw2YjY1W5HknYCOwHesWph8pBgp6Gobi2qnU1uW2aGZE1ps/4GtWDpvNrkjNurBnI7cP8M26+NiCOSVgD7JT1fFK+6QBHWXQCrr1w6+78NmxVdf8qWNAr8GvBguzbFPG0i4hiwh9YlV8zeUuVrn18Bno+IiVYbJS2WtOT8feBGWpdcMXtLSgXd+4GvA1dImpB0S7FpG00v15JWSzpfqWIl8Likp4FvAV+NiId613UbRN2WUiEifrfFurdKqUTEYeDqiv2zIeORGsuKA2lZcSAtKw6kZcWBtKxkOeswUPLsvDLFOssMhZ2sL0xue7ZEwdJa4pDg/D4UbIVyP69+7Heyw+/AZ0jLigNpWXEgLSsOpGXFgbSsOJCWFQfSsuJAWlYcSMuKA2lZUUR+86kkfR/4btPq5cAgzu8e1OcFrZ/bZRHxrnYPyDKQrUgaH8TKF4P6vKC75+aXbMuKA2lZmUuBbFv1Yo4b1OcFXTy3OfMe0obDXDpD2hBwIC0rcyKQkjZLekHSIUm3zXZ/ekXSS5KekXRA0vhs96cKSbslHZP0bMO6SyTtl/Ricbus036yD6SkEeAuYAuwHtguaf3s9qqnro+IDQPwXeS9wOamdbcBj0bEOuDRYnlG2QeS6YpphyLicEScBR4Ats5yn6xJUWbxeNPqrcB9xf37gA922s9cCOSlwMsNyxPFukFwvqDrk0XB1kGzMiJeAShuV3R6QJbTYJu0Ks06KN9VJRd0HRZz4Qw5AaxtWF4DHJmlvvTUEBR0PSppFUBxe6zTA+ZCIJ8A1km6XNI8putS7p3lPlU2JAVd9wI7ivs7gK90ekD2L9kRMSnpVuBhYATYHREHZ7lbvbAS2DN9IQtGgS/O5YKuRWHb64DlkiaA24E7gH8pitz+L/DrHffjoUPLyVx4ybYh4kBaVhxIy4oDaVlxIC0rDqRlxYG0rPw/pCvBzllGUlMAAAAASUVORK5CYII=\n",
-      "text/plain": [
-       "<Figure size 432x288 with 1 Axes>"
-      ]
-     },
-     "metadata": {
-      "needs_background": "light"
-     },
-     "output_type": "display_data"
-    }
-   ],
+   "outputs": [],
    "source": [
     "# Spectrogram visualized of 0th element\n",
     "plt.imshow(X_train[1, :, :, 0])\n",
@@ -710,7 +112,7 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 7,
+   "execution_count": null,
    "metadata": {},
    "outputs": [],
    "source": [
@@ -721,7 +123,7 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 8,
+   "execution_count": null,
    "metadata": {},
    "outputs": [],
    "source": [
@@ -745,7 +147,7 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 9,
+   "execution_count": null,
    "metadata": {},
    "outputs": [],
    "source": [
@@ -757,155 +159,16 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 10,
+   "execution_count": null,
    "metadata": {
     "scrolled": false
    },
-   "outputs": [
-    {
-     "data": {
-      "text/html": [
-       "\n",
-       "                Logging results to <a href=\"https://wandb.com\" target=\"_blank\">Weights & Biases</a> <a href=\"https://docs.wandb.com/integrations/jupyter.html\" target=\"_blank\">(Documentation)</a>.<br/>\n",
-       "                Project page: <a href=\"https://app.wandb.ai/stevenenriquez/uncategorized\" target=\"_blank\">https://app.wandb.ai/stevenenriquez/uncategorized</a><br/>\n",
-       "                Run page: <a href=\"https://app.wandb.ai/stevenenriquez/uncategorized/runs/7sybendi\" target=\"_blank\">https://app.wandb.ai/stevenenriquez/uncategorized/runs/7sybendi</a><br/>\n",
-       "            "
-      ],
-      "text/plain": [
-       "<IPython.core.display.HTML object>"
-      ]
-     },
-     "metadata": {},
-     "output_type": "display_data"
-    },
-    {
-     "name": "stderr",
-     "output_type": "stream",
-     "text": [
-      "Failed to query for notebook name, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable\n"
-     ]
-    },
-    {
-     "name": "stdout",
-     "output_type": "stream",
-     "text": [
-      "Train on 281 samples, validate on 188 samples\n",
-      "Epoch 1/50\n",
-      "281/281 [==============================] - ETA: 2s - loss: 23.0465 - accuracy: 0.093 - ETA: 0s - loss: 16.3184 - accuracy: 0.085 - 0s 2ms/step - loss: 12.3469 - accuracy: 0.1530 - val_loss: 6.6698 - val_accuracy: 0.2766\n",
-      "Epoch 2/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 5.0918 - accuracy: 0.31 - ETA: 0s - loss: 4.7224 - accuracy: 0.26 - 0s 333us/step - loss: 4.5251 - accuracy: 0.2776 - val_loss: 3.5798 - val_accuracy: 0.3138\n",
-      "Epoch 3/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 2.9302 - accuracy: 0.37 - ETA: 0s - loss: 2.8241 - accuracy: 0.31 - 0s 325us/step - loss: 2.7315 - accuracy: 0.3203 - val_loss: 2.8565 - val_accuracy: 0.3032\n",
-      "Epoch 4/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 1.7559 - accuracy: 0.46 - ETA: 0s - loss: 1.7744 - accuracy: 0.48 - 0s 297us/step - loss: 1.7635 - accuracy: 0.4911 - val_loss: 2.7842 - val_accuracy: 0.3777\n",
-      "Epoch 5/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 1.9932 - accuracy: 0.59 - ETA: 0s - loss: 1.4765 - accuracy: 0.55 - 0s 500us/step - loss: 1.3992 - accuracy: 0.5658 - val_loss: 2.4757 - val_accuracy: 0.3511\n",
-      "Epoch 6/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 1.0645 - accuracy: 0.65 - ETA: 0s - loss: 1.3214 - accuracy: 0.63 - 0s 539us/step - loss: 1.2217 - accuracy: 0.6548 - val_loss: 2.8309 - val_accuracy: 0.3617\n",
-      "Epoch 7/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.7947 - accuracy: 0.78 - ETA: 0s - loss: 1.0072 - accuracy: 0.69 - 0s 374us/step - loss: 1.0246 - accuracy: 0.7011 - val_loss: 2.5759 - val_accuracy: 0.4202\n",
-      "Epoch 8/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.8965 - accuracy: 0.75 - ETA: 0s - loss: 1.0584 - accuracy: 0.65 - 0s 335us/step - loss: 0.9949 - accuracy: 0.6797 - val_loss: 2.7374 - val_accuracy: 0.4096\n",
-      "Epoch 9/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.7779 - accuracy: 0.78 - 0s 288us/step - loss: 0.8002 - accuracy: 0.7722 - val_loss: 2.5783 - val_accuracy: 0.4096\n",
-      "Epoch 10/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.5472 - accuracy: 0.81 - ETA: 0s - loss: 0.7422 - accuracy: 0.78 - ETA: 0s - loss: 0.7563 - accuracy: 0.77 - 0s 730us/step - loss: 0.7588 - accuracy: 0.7722 - val_loss: 2.8751 - val_accuracy: 0.3883\n",
-      "Epoch 11/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 1.2013 - accuracy: 0.75 - ETA: 0s - loss: 0.6930 - accuracy: 0.81 - 0s 501us/step - loss: 0.6858 - accuracy: 0.8185 - val_loss: 2.6259 - val_accuracy: 0.3564\n",
-      "Epoch 12/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.3786 - accuracy: 0.93 - ETA: 0s - loss: 0.5313 - accuracy: 0.84 - 0s 320us/step - loss: 0.5298 - accuracy: 0.8470 - val_loss: 2.7889 - val_accuracy: 0.3511\n",
-      "Epoch 13/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.5906 - accuracy: 0.84 - ETA: 0s - loss: 0.5497 - accuracy: 0.84 - 0s 340us/step - loss: 0.5385 - accuracy: 0.8505 - val_loss: 2.6226 - val_accuracy: 0.3989\n",
-      "Epoch 14/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.4711 - accuracy: 0.90 - ETA: 0s - loss: 0.5003 - accuracy: 0.87 - 0s 353us/step - loss: 0.4798 - accuracy: 0.8826 - val_loss: 2.9803 - val_accuracy: 0.3138\n",
-      "Epoch 15/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.5302 - accuracy: 0.84 - 0s 276us/step - loss: 0.4402 - accuracy: 0.9004 - val_loss: 2.6732 - val_accuracy: 0.4043\n",
-      "Epoch 16/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2521 - accuracy: 0.93 - ETA: 0s - loss: 0.3664 - accuracy: 0.89 - 0s 327us/step - loss: 0.3706 - accuracy: 0.8897 - val_loss: 2.9172 - val_accuracy: 0.3457\n",
-      "Epoch 17/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.3003 - accuracy: 0.87 - 0s 261us/step - loss: 0.3737 - accuracy: 0.9004 - val_loss: 2.7488 - val_accuracy: 0.4043\n",
-      "Epoch 18/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2518 - accuracy: 0.90 - ETA: 0s - loss: 0.3444 - accuracy: 0.91 - 0s 328us/step - loss: 0.3300 - accuracy: 0.9217 - val_loss: 2.8965 - val_accuracy: 0.4255\n",
-      "Epoch 19/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2022 - accuracy: 0.93 - ETA: 0s - loss: 0.3102 - accuracy: 0.91 - 0s 381us/step - loss: 0.3142 - accuracy: 0.9146 - val_loss: 3.0782 - val_accuracy: 0.3830\n",
-      "Epoch 20/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.4091 - accuracy: 0.87 - ETA: 0s - loss: 0.2662 - accuracy: 0.94 - 0s 349us/step - loss: 0.2553 - accuracy: 0.9466 - val_loss: 2.9722 - val_accuracy: 0.3989\n",
-      "Epoch 21/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.3199 - accuracy: 0.84 - ETA: 0s - loss: 0.2778 - accuracy: 0.92 - 0s 328us/step - loss: 0.2780 - accuracy: 0.9288 - val_loss: 3.1543 - val_accuracy: 0.3777\n",
-      "Epoch 22/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2065 - accuracy: 0.93 - ETA: 0s - loss: 0.2018 - accuracy: 0.95 - 0s 312us/step - loss: 0.2135 - accuracy: 0.9573 - val_loss: 3.0016 - val_accuracy: 0.3723\n",
-      "Epoch 23/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.1530 - accuracy: 1.00 - ETA: 0s - loss: 0.1672 - accuracy: 0.96 - 0s 391us/step - loss: 0.1630 - accuracy: 0.9680 - val_loss: 2.9483 - val_accuracy: 0.4149\n",
-      "Epoch 24/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0950 - accuracy: 1.00 - ETA: 0s - loss: 0.1391 - accuracy: 0.97 - ETA: 0s - loss: 0.1322 - accuracy: 0.98 - 0s 742us/step - loss: 0.1495 - accuracy: 0.9786 - val_loss: 3.1443 - val_accuracy: 0.3723\n",
-      "Epoch 25/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2155 - accuracy: 0.96 - ETA: 0s - loss: 0.1644 - accuracy: 0.96 - 0s 345us/step - loss: 0.1596 - accuracy: 0.9680 - val_loss: 3.1408 - val_accuracy: 0.3777\n",
-      "Epoch 26/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2744 - accuracy: 0.96 - 0s 279us/step - loss: 0.1713 - accuracy: 0.9644 - val_loss: 3.3056 - val_accuracy: 0.3883\n",
-      "Epoch 27/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0661 - accuracy: 1.00 - ETA: 0s - loss: 0.1034 - accuracy: 0.98 - 0s 358us/step - loss: 0.1384 - accuracy: 0.9786 - val_loss: 3.1630 - val_accuracy: 0.3564\n",
-      "Epoch 28/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0931 - accuracy: 1.00 - 0s 334us/step - loss: 0.1158 - accuracy: 0.9786 - val_loss: 3.2077 - val_accuracy: 0.3936\n",
-      "Epoch 29/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0765 - accuracy: 1.00 - ETA: 0s - loss: 0.1380 - accuracy: 0.97 - ETA: 0s - loss: 0.1156 - accuracy: 0.98 - 0s 595us/step - loss: 0.1128 - accuracy: 0.9822 - val_loss: 3.3168 - val_accuracy: 0.3989\n",
-      "Epoch 30/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0909 - accuracy: 1.00 - ETA: 0s - loss: 0.0954 - accuracy: 0.98 - 0s 515us/step - loss: 0.0994 - accuracy: 0.9893 - val_loss: 3.3483 - val_accuracy: 0.3723\n",
-      "Epoch 31/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0612 - accuracy: 1.00 - 0s 258us/step - loss: 0.0910 - accuracy: 0.9786 - val_loss: 3.3935 - val_accuracy: 0.3723\n",
-      "Epoch 32/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0532 - accuracy: 1.00 - ETA: 0s - loss: 0.1474 - accuracy: 0.98 - 0s 411us/step - loss: 0.1534 - accuracy: 0.9822 - val_loss: 3.4210 - val_accuracy: 0.3723\n",
-      "Epoch 33/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2349 - accuracy: 0.93 - ETA: 0s - loss: 0.1145 - accuracy: 0.98 - 0s 453us/step - loss: 0.1363 - accuracy: 0.9822 - val_loss: 3.5561 - val_accuracy: 0.4096\n",
-      "Epoch 34/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.1375 - accuracy: 0.96 - ETA: 0s - loss: 0.1624 - accuracy: 0.95 - 0s 365us/step - loss: 0.1564 - accuracy: 0.9537 - val_loss: 3.7636 - val_accuracy: 0.3883\n",
-      "Epoch 35/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.1473 - accuracy: 0.96 - ETA: 0s - loss: 0.1620 - accuracy: 0.94 - 0s 436us/step - loss: 0.1161 - accuracy: 0.9680 - val_loss: 3.4313 - val_accuracy: 0.3617\n",
-      "Epoch 36/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.1176 - accuracy: 0.96 - ETA: 0s - loss: 0.1088 - accuracy: 0.98 - 0s 341us/step - loss: 0.1037 - accuracy: 0.9822 - val_loss: 3.5027 - val_accuracy: 0.3404\n",
-      "Epoch 37/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0528 - accuracy: 1.00 - 0s 276us/step - loss: 0.0928 - accuracy: 0.9786 - val_loss: 3.4027 - val_accuracy: 0.3830\n",
-      "Epoch 38/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0446 - accuracy: 1.00 - ETA: 0s - loss: 0.1070 - accuracy: 0.98 - 0s 527us/step - loss: 0.1131 - accuracy: 0.9858 - val_loss: 3.4673 - val_accuracy: 0.4043\n",
-      "Epoch 39/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0330 - accuracy: 1.00 - ETA: 0s - loss: 0.0613 - accuracy: 0.99 - 0s 518us/step - loss: 0.0732 - accuracy: 0.9929 - val_loss: 3.5865 - val_accuracy: 0.3830\n",
-      "Epoch 40/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0310 - accuracy: 1.00 - 0s 257us/step - loss: 0.0709 - accuracy: 0.9858 - val_loss: 3.4783 - val_accuracy: 0.3723\n",
-      "Epoch 41/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.2000 - accuracy: 0.96 - 0s 248us/step - loss: 0.0775 - accuracy: 0.9858 - val_loss: 3.5490 - val_accuracy: 0.3777\n",
-      "Epoch 42/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0373 - accuracy: 1.00 - ETA: 0s - loss: 0.0730 - accuracy: 0.98 - 0s 363us/step - loss: 0.0740 - accuracy: 0.9858 - val_loss: 3.8505 - val_accuracy: 0.3723\n",
-      "Epoch 43/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0341 - accuracy: 1.00 - ETA: 0s - loss: 0.0645 - accuracy: 0.98 - 0s 449us/step - loss: 0.0596 - accuracy: 0.9893 - val_loss: 3.6512 - val_accuracy: 0.3777\n",
-      "Epoch 44/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0223 - accuracy: 1.00 - 0s 252us/step - loss: 0.0542 - accuracy: 0.9929 - val_loss: 3.6441 - val_accuracy: 0.3670\n",
-      "Epoch 45/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0308 - accuracy: 1.00 - 0s 275us/step - loss: 0.0468 - accuracy: 0.9893 - val_loss: 3.6158 - val_accuracy: 0.3723\n",
-      "Epoch 46/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0172 - accuracy: 1.00 - ETA: 0s - loss: 0.0425 - accuracy: 0.99 - 0s 486us/step - loss: 0.0504 - accuracy: 0.9929 - val_loss: 3.6831 - val_accuracy: 0.3777\n",
-      "Epoch 47/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0248 - accuracy: 1.00 - ETA: 0s - loss: 0.1069 - accuracy: 0.99 - 0s 357us/step - loss: 0.0945 - accuracy: 0.9929 - val_loss: 3.7183 - val_accuracy: 0.3830\n",
-      "Epoch 48/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0305 - accuracy: 1.00 - 0s 257us/step - loss: 0.0545 - accuracy: 0.9858 - val_loss: 3.7581 - val_accuracy: 0.3989\n",
-      "Epoch 49/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0211 - accuracy: 1.00 - ETA: 0s - loss: 0.0681 - accuracy: 0.98 - 0s 358us/step - loss: 0.0656 - accuracy: 0.9822 - val_loss: 3.9350 - val_accuracy: 0.3723\n",
-      "Epoch 50/50\n",
-      "281/281 [==============================] - ETA: 0s - loss: 0.0954 - accuracy: 0.96 - ETA: 0s - loss: 0.0738 - accuracy: 0.98 - 0s 555us/step - loss: 0.0570 - accuracy: 0.9893 - val_loss: 3.7512 - val_accuracy: 0.3670\n"
-     ]
-    },
-    {
-     "data": {
-      "text/plain": [
-       "<keras.callbacks.callbacks.History at 0x16ff36d33c8>"
-      ]
-     },
-     "execution_count": 10,
-     "metadata": {},
-     "output_type": "execute_result"
-    }
-   ],
+   "outputs": [],
    "source": [
     "wandb.init()\n",
-    "\n",
+    "print(y_train_hot.shape)\n",
+    "print(labels.shape)\n",
+    "print(X_train.shape)\n",
     "# Train the CNN model\n",
     "#    X_train: Input data\n",
     "#    y_train_hot: Target data\n",
@@ -914,17 +177,9 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 11,
+   "execution_count": null,
    "metadata": {},
-   "outputs": [
-    {
-     "name": "stdout",
-     "output_type": "stream",
-     "text": [
-      "Model has been saved.\n"
-     ]
-    }
-   ],
+   "outputs": [],
    "source": [
     "# Save the keras model\n",
     "model.save(\"ant_cnn_model.h5\")\n",
@@ -940,7 +195,7 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 13,
+   "execution_count": null,
    "metadata": {
     "scrolled": true
    },
@@ -954,34 +209,9 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 14,
+   "execution_count": null,
    "metadata": {},
-   "outputs": [
-    {
-     "name": "stdout",
-     "output_type": "stream",
-     "text": [
-      "Model: \"sequential_1\"\n",
-      "_________________________________________________________________\n",
-      "Layer (type)                 Output Shape              Param #   \n",
-      "=================================================================\n",
-      "conv2d_1 (Conv2D)            (None, 18, 9, 32)         320       \n",
-      "_________________________________________________________________\n",
-      "max_pooling2d_1 (MaxPooling2 (None, 9, 4, 32)          0         \n",
-      "_________________________________________________________________\n",
-      "flatten_1 (Flatten)          (None, 1152)              0         \n",
-      "_________________________________________________________________\n",
-      "dense_1 (Dense)              (None, 128)               147584    \n",
-      "_________________________________________________________________\n",
-      "dense_2 (Dense)              (None, 10)                1290      \n",
-      "=================================================================\n",
-      "Total params: 149,194\n",
-      "Trainable params: 149,194\n",
-      "Non-trainable params: 0\n",
-      "_________________________________________________________________\n"
-     ]
-    }
-   ],
+   "outputs": [],
    "source": [
     "# Summarize the model\n",
     "model.summary()"
@@ -989,68 +219,77 @@
   },
   {
    "cell_type": "code",
-   "execution_count": 15,
+   "execution_count": null,
    "metadata": {},
-   "outputs": [
-    {
-     "name": "stdout",
-     "output_type": "stream",
-     "text": [
-      "PREDICTED VALUES\n",
-      "\n",
-      " bus :  0.00002306\n",
-      "\n",
-      " car_horn :  0.98330659\n",
-      "\n",
-      " chainsaw :  0.00023836\n",
-      "\n",
-      " cow :  0.00675107\n",
-      "\n",
-      " engine :  0.00007791\n",
-      "\n",
-      " footsteps :  0.00000021\n",
-      "\n",
-      " hand_saw :  0.00959078\n",
-      "\n",
-      " hen :  0.00000000\n",
-      "\n",
-      " rooster :  0.00001190\n",
-      "\n",
-      " siren :  0.00000016\n",
-      "\n",
-      "\n",
-      "GUESS:  car_horn\n"
-     ]
-    }
-   ],
+   "outputs": [],
    "source": [
     "## Running the model\n",
     "\n",
-    "# Convert wav to MFCC\n",
-    "prediction_data = wav2mfcc('./prediction/cow.wav')\n",
+    "n_mfcc = 20\n",
+    "max_len = 11\n",
+    "# convert file to wav2mfcc\n",
+    "# Mel-frequency cepstral coefficients\n",
+    "file_path = \"./prediction/nature_sc.wav\"\n",
+    "big_wave, sr = librosa.load(file_path, mono=True, sr=None)\n",
+    "#print(wave.shape, sr)\n",
+    "\n",
+    "classification = []\n",
+    "\n",
+    "for sec_index in range( int(big_wave.shape[0] / sr) ) :\n",
+    "    start_sec = sec_index\n",
+    "    end_sec = sec_index + 1\n",
+    "    \n",
+    "    sec_to_trim = np.array( [ float(start_sec), float(end_sec) ] )\n",
+    "    print(sec_to_trim)\n",
+    "    sec_to_trim = np.ceil( sec_to_trim * sr )\n",
+    "\n",
+    "    wave = big_wave[int(sec_to_trim[0]) : int(sec_to_trim[1])]\n",
+    "    print(wave)\n",
+    "\n",
+    "    wave = np.asfortranarray(wave[::3])\n",
+    "    mfcc = librosa.feature.mfcc(wave, sr=16000, n_mfcc=n_mfcc)\n",
+    "\n",
+    "    # If maximum length exceeds mfcc lengths then pad the remaining ones\n",
+    "    if (max_len > mfcc.shape[1]):\n",
+    "        pad_width = max_len - mfcc.shape[1]\n",
+    "        mfcc = np.pad(mfcc, pad_width=((0, 0), (0, pad_width)), mode='constant')\n",
+    "\n",
+    "    # Else cutoff the remaining parts\n",
+    "    else:\n",
+    "        mfcc = mfcc[:, :max_len]\n",
+    "\n",
+    "    # Convert wav to MFCC\n",
+    "    prediction_data = wav2mfcc('./prediction/nature_sc.wav')\n",
+    "    prediction_data = mfcc\n",
+    "    print(prediction_data.shape)\n",
+    "    #print(wav2mfcc())\n",
+    "    # Reshape to 4 dimensions\n",
+    "    prediction_data = prediction_data.reshape(1, config.buckets, config.max_len, channels)\n",
+    "    prediction_data = prediction_data.reshape(1, 20, config.max_len, channels)\n",
     "\n",
-    "# Reshape to 4 dimensions\n",
-    "prediction_data = prediction_data.reshape(1, config.buckets, config.max_len, channels)\n",
+    "    # Run the model on the inputted file\n",
+    "    predicted = loaded_model.predict(prediction_data)\n",
     "\n",
-    "# Run the model on the inputted file\n",
-    "predicted = loaded_model.predict(prediction_data)\n",
+    "    # Output the prediction values for each class\n",
+    "    print ('PREDICTED VALUES')\n",
+    "    labels_indices = range(len(labels))\n",
+    "    max_value = 0\n",
+    "    max_value_index = 0\n",
+    "    for index in labels_indices:\n",
+    "        print('\\n', labels[index], \": \", '%.08f' % predicted[0,index])\n",
+    "        if predicted[0,index] > max_value:\n",
+    "            max_value_index = index\n",
+    "            max_value = predicted[0,index]\n",
     "\n",
-    "# Output the prediction values for each class\n",
-    "print ('PREDICTED VALUES')\n",
-    "labels_indices = range(len(labels))\n",
-    "max_value = 0\n",
-    "max_value_index = 0\n",
-    "for index in labels_indices:\n",
-    "    print('\\n', labels[index], \": \", '%.08f' % predicted[0,index])\n",
-    "    if predicted[0,index] > max_value:\n",
-    "        max_value_index = index\n",
-    "        max_value = predicted[0,index]\n",
+    "    # Output the prediction\n",
+    "    if max_value < 0.5:\n",
+    "        print(\"GUESS: Nothing\")\n",
+    "        classification.append( { \"class\" : \"Nothing\", \"timestamp\" : start_sec } )\n",
+    "    else:\n",
+    "        print('\\n\\nGUESS: ', labels[max_value_index])\n",
+    "        classification.append( { \"class\" : labels[max_value_index], \"timestamp\" : start_sec } )\n",
     "\n",
-    "# Output the prediction\n",
-    "if max_value < 0.5:\n",
-    "    print(\"GUESS: Nothing\")\n",
-    "else:\n",
-    "    print('\\n\\nGUESS: ', labels[max_value_index])"
+    "print(classification)"
    ]
   },
   {
@@ -1077,7 +316,7 @@
    "name": "python",
    "nbconvert_exporter": "python",
    "pygments_lexer": "ipython3",
-   "version": "3.8.2"
+   "version": "3.7.4"
   }
  },
  "nbformat": 4,
diff --git a/ant-cnn/preprocess.py b/ant-cnn/preprocess.py
index e5fe230..9b18914 100644
--- a/ant-cnn/preprocess.py
+++ b/ant-cnn/preprocess.py
@@ -18,7 +18,7 @@ def get_labels(path=DATA_PATH):
 
 # convert file to wav2mfcc
 # Mel-frequency cepstral coefficients
-def wav2mfcc(file_path, n_mfcc=20, max_len=11):
+def wav2mfcc(file_path, n_mfcc=30, max_len=11):
     wave, sr = librosa.load(file_path, mono=True, sr=None)
     wave = np.asfortranarray(wave[::3])
     mfcc = librosa.feature.mfcc(wave, sr=16000, n_mfcc=n_mfcc)
